config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "schedules#index"
  resources :schedules do
    resources :sub_schedules
    resources :comments, only: :create
  end
  resources :users,only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :schedule

  validates :text, presence: true
end

app/models/importance.rb
class Importance < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '★' },
    { id: 3, name: '★★' },
    { id: 4, name: '★★★' },
    { id: 5, name: '★★★★' },
    { id: 6, name: '★★★★★' }
  ]

  include ActiveHash::Associations
  has_many :schedules
  has_many :sub_schedules
end

app/models/limit.rb
class Limit < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '0:00' },
    { id: 3, name: '1:00' },
    { id: 4, name: '2:00' },
    { id: 5, name: '3:00' },
    { id: 6, name: '4:00' },
    { id: 7, name: '5:00' },
    { id: 8, name: '6:00' },
    { id: 9, name: '7:00' },
    { id: 10, name: '8:00' },
    { id: 11, name: '9:00' },
    { id: 12, name: '10:00' },
    { id: 13, name: '11:00' },
    { id: 14, name: '12:00' },
    { id: 15, name: '13:00' },
    { id: 16, name: '14:00' },
    { id: 17, name: '15:00' },
    { id: 18, name: '16:00' },
    { id: 19, name: '17:00' },
    { id: 20, name: '18:00' },
    { id: 21, name: '19:00' },
    { id: 22, name: '20:00' },
    { id: 23, name: '21:00' },
    { id: 24, name: '22:00' },
    { id: 25, name: '23:00' },
    { id: 26, name: '24:00' }
  ]

  include ActiveHash::Associations
  has_many :schedules
  has_many :sub_schedules
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many   :comments
  has_many   :sub_schedules
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :importance
  belongs_to :limit

  with_options numericality: { other_than: 1 } do
    validates :time_id
    validates :importance_id
  end

  validates :title,   presence: true
  validates :date_id, presence: true
end

app/models/sub_schedule.rb
class SubSchedule < ApplicationRecord
  belongs_to :schedule


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :importance
  belongs_to :limit


  with_options presence: true do
    validates :title
    validates :date_id
    validates :importance_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :schedules
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to schedule_path(@comment.schedule.id)
    else
      @schedule = @comment.schedule
      @comments = @schedule.comments
      render "schedules/show"
    end
  end

  private

  def comment_params
    params.permit(:text).merge(user_id: current_user.id, schedule_id: params[:schedule_id])
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all.order("created_at DESC")
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    redirect_to root_path
  end

  def show
    @schedule = Schedule.find(params[:id])
    @sub_schedule = SubSchedule.new
    @sub_schedule = SubSchedule.find_by(params[@sub_schedule.id])
    @sub_schedule = SubSchedule.where(params[:id])
    @comment = Comment.new
    @comment = @schedule.comments.includes(:user)
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    @schedule.update(schedule_params)
    if @schedule.save
      redirect_to schedule_path
    else
      render :edit
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :date_id, :time_id, :text, :importance_id).merge(user_id: current_user.id)
  end
end

app/controllers/sub_schedules_controller.rb
class SubSchedulesController < ApplicationController
  def index
  end

  def new
    @sub_schedule = SubSchedule.new
  end

  def create
    @sub_schedule = SubSchedule.new(sub_schedule_params)
    if @sub_schedule.save
      redirect_to schedule_path(@sub_schedule.schedule.id)
    else
      render :new
    end
  end

  def destroy
  end

  def show
  end

  def edit
  end

  def update
  end

  private

  def sub_schedule_params
    params.require(:sub_schedule).permit(:title, :date_id, :time_id, :text, :importance_id).merge(schedule_id: params[:schedule_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/sub_schedules_helper.rb
module SubSchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Stylehacker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "Sign Out", destroy_user_session_path,method: :delete, class: :nav__logout %>
              <%= link_to "New Schedule", new_schedule_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "Sign In", new_user_session_path, class: :nav__btn %>
              <%= link_to "Sign Up", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © STYLE HACKER All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with model: schedule, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "Title" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <div class='form-text-wrap'>
      <label class="form-text">Year, Month, Date</label>
    </div>
    <div class='input-limit-wrap'>
      <%= raw sprintf(f.date_select :date_id, use_month_numbers: true, start_year: Time.now.year, end_year: (Time.now.year + 10), prompt:"--") %>

    </div>
  </div>

  <div class="field">
    <%= f.label :time_id, "Time" %><br />
    <%= f.collection_select(:time_id, Limit.all, :id, :name, {}, {class: :form__text, id:"prototype_concept"}) %>
  </div>

    <div class="field">
    <%= f.label :importance_id, "Importance" %><br />
    <%= f.collection_select(:importance_id, Importance.all, :id, :name, {}, {class: :form__text, id:"prototype_concept"}) %>
  </div>

    <div class="field">
    <%= f.label :text, "Memo" %><br />
    <%= f.text_area :text, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: :form__btn  %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div class="card">
  <div class="card__body">
    <%= link_to "#{schedule.title}", schedule_path(schedule.id), class: :card__title%>
    <div class="card__text">
      <%= "#{schedule.text}" %>
    </div>
  </div>
  <div class="card__summary">
    <%= "#{schedule.date_id}" %>
  </div>
  <div class="card__summary">
    <%= "#{schedule.importance.name}" %>
  </div>
</div>

app/views/schedules/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">Schedule Edit</h2>
      <%= render partial:"form", locals: { schedule: @schedule } %>
    </div>
  </div>
</div>

app/views/schedules/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= link_to "#{current_user.name}'s schedule", user_path(current_user.id), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial:"schedule", collection:@schedules %>
    </div>
  </div>
</main>

app/views/schedules/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">New Schedule</h2>
        <%= render partial:"form", locals: { schedule: @schedule } %>
    </div>
  </div>
</div>

app/views/schedules/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= "#{@schedule.title}" %>
      </p>
      <%= link_to "by #{@schedule.user.name}", user_path, class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @schedule.user_id %>
        <div class="prototype__manage">
          <%= link_to "Edit", edit_schedule_path(@schedule.id), class: :prototype__btn %>
          <%= link_to "Delete", schedule_path(@schedule.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">Limit</p>
          <p class="detail__message">
            <%= "#{@schedule.date_id}" %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">Importance</p>
          <p class="detail__message">
            <%= "#{@schedule.importance.name}" %>
          </p>
        </div>
        <div class="prototype__detail">
          <b class="dateil__title">Task</b>
          <p class="dateil__message">
            <%= link_to "Create Task", new_schedule_sub_schedule_path(@schedule.id), class: :nav__btn %>
          </p>
        </div>
        <div class="sub_schedule_lists">
          <% @sub_schedule.each do |sub_schedule| %>
            <li class="sub_schedule_list">
              <%= "#{sub_schedule.title}"%>
              <%= "#{sub_schedule.date_id}"%>
              <%= "#{sub_schedule.time_id}"%>
              <%= "#{sub_schedule.importance.name}"%>
              <div class="sub_schedule_text">
                <%= "#{sub_schedule.text}"%>
              </div>
            </li>
          <% end %>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with url: schedule_comments_path(@schedule.id), local: true do |f|%>
            <div class="field">
              <%= f.label :text, "Comments" %><br />
              <%= f.text_field :text, id:"comment_text" %>
            </div>
            <div class="actions">
              <%= f.submit "Comment", class: :form__btn  %>
            </div>
          <% end  %>
        <% end %>
        <ul class="comments_lists">
          <% @comment.each do |comment| %>
            <li class="comments_list">
              <%= "#{comment.text}"%>
              <%= link_to "#{comment.user.name}", user_path(@schedule.user.id), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/sub_schedules/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">New Task</h2>
        <%= form_with model: @sub_schedule, url: schedule_sub_schedules_path, method: :post, local: true do |f|%>
          <div class="field">
           <%= f.label :title, "Title" %><br />
           <%= f.text_field :title, id:"prototype_title" %>
          </div>

          <div class="field">
            <div class='form-text-wrap'>
              <label class="form-text">Year, Month, Date</label>
            </div>
            <div class='input-limit-wrap'>
              <%= raw sprintf(f.date_select :date_id, use_month_numbers: true, start_year: Time.now.year, end_year: (Time.now.year + 10), prompt:"--") %>
            </div>
          </div>

          <div class="field">
            <%= f.label :time_id, "Time" %><br />
            <%= f.collection_select(:time_id, Limit.all, :id, :name, {}, {class: :form__text, id:"prototype_concept"}) %>
          </div>

          <div class="field">
            <%= f.label :importance_id, "Importance" %><br />
            <%= f.collection_select(:importance_id, Importance.all, :id, :name, {}, {class: :form__text, id:"prototype_concept"}) %>
          </div>

          <div class="field">
            <%= f.label :text, "Memo" %><br />
            <%= f.text_area :text, class: :form__text, id:"prototype_concept" %>
          </div>

          <div class="actions">
            <%= f.submit "Save", class: :form__btn  %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">

      <h2 class="page-heading">
        <%= "#{ @user.name}'s Schedule" %>
      </h2>
      <div class="user__card">
        <%= render partial: "schedules/schedule", collection: @user.schedules %>
      </div>
    </div>
  </div>
</div>